WITH ValorMedioCliente AS (
    SELECT
        P.CLIENTE_ID,
        AVG(PR.PRECO_PRODUTO * PI.QUANTIDADE) AS VALOR_MEDIO
    FROM
        PEDIDOS P
        JOIN PEDIDO_ITENS PI ON P.PEDIDO_ID = PI.PEDIDO_ID
        JOIN PRODUTOS PR ON PI.PRODUTO_ID = PR.PRODUTO_ID
    GROUP BY
        P.CLIENTE_ID
),

TotalItensPedido AS (
    SELECT
        P.PEDIDO_ID,
        P.CLIENTE_ID,
        P.DATA_PEDIDO,
        P.TOTAL_PEDIDO,
        SUM(PI.QUANTIDADE * PR.PRECO_PRODUTO) AS TOTAL_ITENS
    FROM
        PEDIDOS P
        JOIN PEDIDO_ITENS PI ON P.PEDIDO_ID = PI.PEDIDO_ID
        JOIN PRODUTOS PR ON PI.PRODUTO_ID = PR.PRODUTO_ID
    GROUP BY
        P.PEDIDO_ID, P.CLIENTE_ID, P.DATA_PEDIDO, P.TOTAL_PEDIDO
),
  
PedidosValidos AS (
    SELECT
        TIP.PEDIDO_ID,
        TIP.CLIENTE_ID,
        TIP.DATA_PEDIDO,
        TIP.TOTAL_PEDIDO,
        TIP.TOTAL_ITENS
    FROM
        TotalItensPedido TIP
        JOIN ValorMedioCliente VMC ON TIP.CLIENTE_ID = VMC.CLIENTE_ID
    WHERE
        EXISTS (
            SELECT 1
            FROM PEDIDO_ITENS PI
            JOIN PRODUTOS PR ON PI.PRODUTO_ID = PR.PRODUTO_ID
            WHERE PI.PEDIDO_ID = TIP.PEDIDO_ID
            AND PR.PRECO_PRODUTO > VMC.VALOR_MEDIO
        )
),

PedidosComSatisfacao AS (
    SELECT
        PV.CLIENTE_ID,
        PV.PEDIDO_ID,
        PV.DATA_PEDIDO,
        PV.TOTAL_PEDIDO,
        PV.TOTAL_ITENS,
        CASE
            WHEN PV.TOTAL_ITENS / PV.TOTAL_PEDIDO > 0.75 THEN 'Alta'
            WHEN PV.TOTAL_ITENS / PV.TOTAL_PEDIDO BETWEEN 0.5 AND 0.75 THEN 'Média'
            ELSE 'Baixa'
        END AS INDICE_SATISFACAO
    FROM
        PedidosValidos PV
    WHERE
        PV.TOTAL_ITENS > 0.5 * PV.TOTAL_PEDIDO
)

SELECT
    PCS.CLIENTE_ID,
    C.NOME_CLIENTE,
    PCS.PEDIDO_ID,
    PCS.DATA_PEDIDO,
    PCS.TOTAL_PEDIDO,
    PCS.TOTAL_ITENS,
    PCS.INDICE_SATISFACAO
FROM
    PedidosComSatisfacao PCS
    JOIN CLIENTES C ON PCS.CLIENTE_ID = C.CLIENTE_ID
ORDER BY
    PCS.CLIENTE_ID,
    PCS.DATA_PEDIDO DESC;
